//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHJ_hTlVM_MH-2V4vCpSKsClOaoesAms',
    appId: '1:209777607736:web:73b05254dedde7303312cd',
    messagingSenderId: '209777607736',
    projectId: 'diet-planner-app-abc',
    authDomain: 'diet-planner-app-abc.firebaseapp.com',
    storageBucket: 'diet-planner-app-abc.firebasestorage.app',
    measurementId: 'G-5WYHECNPEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshMFbqgK80l3slhzQ67mfCP6PNUZgRvQ',
    appId: '1:209777607736:android:929a5ee455910eb83312cd',
    messagingSenderId: '209777607736',
    projectId: 'diet-planner-app-abc',
    storageBucket: 'diet-planner-app-abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB69gFN4Vv_Qtu24HMtIbAdTHaRosp0rDs',
    appId: '1:209777607736:ios:1ea90597f5035ca53312cd',
    messagingSenderId: '209777607736',
    projectId: 'diet-planner-app-abc',
    storageBucket: 'diet-planner-app-abc.firebasestorage.app',
    iosBundleId: 'com.team.dietplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB69gFN4Vv_Qtu24HMtIbAdTHaRosp0rDs',
    appId: '1:209777607736:ios:d3497cda6227d73c3312cd',
    messagingSenderId: '209777607736',
    projectId: 'diet-planner-app-abc',
    storageBucket: 'diet-planner-app-abc.firebasestorage.app',
    iosBundleId: 'com.example.dietApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqHJ_hTlVM_MH-2V4vCpSKsClOaoesAms',
    appId: '1:209777607736:web:ec20ced577192aab3312cd',
    messagingSenderId: '209777607736',
    projectId: 'diet-planner-app-abc',
    authDomain: 'diet-planner-app-abc.firebaseapp.com',
    storageBucket: 'diet-planner-app-abc.firebasestorage.app',
    measurementId: 'G-M57CFYNDNV',
  );
}
